services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: backend-kit-edu
    container_name: kit-edu-backend
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - ../backend/.env
    depends_on:
      - postgres-kit-edu
      - minio

  ai-worker:
    image: backend-kit-edu
    ports:
      - "4001:4001"
    env_file:
      - ../backend/.env
    depends_on:
      - postgres-kit-edu
    restart: unless-stopped
    command: ["node", "dist/ai-works/main.js"]

  postgres-kit-edu:
    image: postgres:16
    container_name: postgres-kit-edu
    env_file: ./.env.postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-1:/var/lib/postgresql/data
    mem_limit: 512m

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_BUCKET: tickets
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    mem_limit: 512m

  nginx-kit-edu:
    container_name: nginx-kit-edu
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    mem_limit: 512m

volumes:
  postgres-data-1:
